### ISSUE TITLE
在使用命令后服务器命令执行成功但是mirai报错，qq也没有反馈

### ISSUE THREAD

**Issue by NekoEpisode** [limbang/mirai-console-rcon-plugin#1]
问题如上
版本0.1.3.Mirai2
服务器版本：1.12.2
rcon链接地址：127.0.0.1:16666
以下为报错内容
 command owned by MinecraftRemoteConsole v0.1.2 with NormalMember(***********)
java.lang.IllegalArgumentException: message is empty
        at net.mamoe.mirai.internal.contact.AbstractUserKt.sendMessageImpl(AbstractUser.kt:258)
        at net.mamoe.mirai.internal.contact.CommonGroupImpl.sendMessage$suspendImpl(GroupImpl.kt:219)
        at net.mamoe.mirai.internal.contact.CommonGroupImpl.sendMessage(GroupImpl.kt)
        at net.mamoe.mirai.console.command.MemberCommandSender.sendMessage$suspendImpl(CommandSender.kt:687)
        at net.mamoe.mirai.console.command.MemberCommandSender.sendMessage(CommandSender.kt)
        at net.mamoe.mirai.console.command.MemberCommandSender.sendMessage$suspendImpl(CommandSender.kt:684)
        at net.mamoe.mirai.console.command.MemberCommandSender.sendMessage(CommandSender.kt)
        at mirai-console-rcon-plugin-0.1.3.mirai2.jar//top.limbang.minecraft.PluginCompositeCommand.cmd(MinecraftRemoteConsole.kt:159)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
        at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:159)
        at kotlin.reflect.full.KCallables.callSuspendBy(KCallables.kt:74)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invokeSuspend(CommandReflector.kt:337)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
        at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call$suspendImpl(CommandSignature.kt:88)
        at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call(CommandSignature.kt)
        at net.mamoe.mirai.console.internal.command.CommandManagerImplKt.executeCommandImpl(CommandManagerImpl.kt:168)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand$suspendImpl(CommandManager.kt:130)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand(CommandManager.kt)
        at net.mamoe.mirai.console.command.CommandManager$INSTANCE.executeCommand(CommandManager.kt)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand$default(CommandManager.kt:125)
        at chat-command-0.6.0.mirai2.jar//net.mamoe.mirai.console.plugins.chat.command.PluginMain.handleCommand(PluginMain.kt:98)
        at chat-command-0.6.0.mirai2.jar//net.mamoe.mirai.console.plugins.chat.command.PluginMain$onEnable$2$1.invokeSuspend(PluginMain.kt:66)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**Comment by NekoEpisode** [comment]
问题是在qq群中执行子级命令就会出现错误
例如
say a
服务器就会有响应但是mirai报错
只有单极命令没问题，例如8747828会正常显示未知的命令

**Comment by limbang** [comment]
等下我试试
